/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report which modules are enabled and how this server was built
         * @description Answers from the process configuration: the enabled modules in the
         *     order they were configured, the binary version, whether an LLM and
         *     Telegram are configured, and the timezone dates are rendered in. The
         *     frontend mounts only what is listed.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report that this server is serving
         * @description Answers from the process itself and touches no database, no file store
         *     and no network, so a 200 means the binary is up and nothing more. It is
         *     what a container health check and the dev proxy poll.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Config: {
            /** @description Enabled feature modules in the configured order. */
            modules: string[];
            /** @description The binary version `norte version` prints. */
            version: string;
            /** @description True when NORTE_LLM_URL is set. */
            llm: boolean;
            /** @description True when NORTE_TELEGRAM_TOKEN is set. */
            telegram: boolean;
            /** @description The IANA timezone dates are rendered in. */
            timezone: string;
        };
        Health: {
            /**
             * @description Always "ok"; a server that cannot answer does not answer at all.
             * @enum {string}
             */
            status: "ok";
        };
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /**
             * @description Stable, machine-readable reason. The frontend branches on this;
             *     the message is for a person.
             * @example invalid_request
             */
            code: string;
            /** @description What went wrong, in one sentence, safe to show. */
            message: string;
            /**
             * @description The input the failure is attributable to, when it is attributable
             *     to exactly one. Absent otherwise.
             * @example kind
             */
            field?: string;
            /**
             * @description The X-Request-Id of the request that failed, so an error a person
             *     reports can be matched to the log line that recorded it.
             */
            request_id: string;
        };
    };
    responses: {
        /**
         * @description Every failure in one envelope, whether it came from validating the
         *     request against this contract or from the domain behind it.
         */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The enabled modules and the build's capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Config"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The server is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
