/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/library/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List saved links
         * @description Summaries, never the extracted HTML or text. Every sort is a total
         *     order with the id breaking ties. The cursor encodes the sort position
         *     and a hash of the filters, and a cursor presented with different
         *     filters or sort is refused. With q the order is the full-text rank,
         *     then id, and an explicit sort together with q is refused.
         *
         *     view=now is not a shelf: it reads every status, keeps only unread
         *     items and orders them by how closely they relate to what the person is
         *     focused on, so it carries its own order and refuses q, an explicit
         *     sort and unread=false.
         */
        get: operations["listLibraryItems"];
        put?: never;
        /**
         * Save a link to the library
         * @description Stores the HTML snapshot when one came with the request, then records
         *     the item, its registry row, its file reference, its links and its
         *     extraction job in one transaction. A save whose canonical URL already
         *     exists answers 200 with the existing id and applies the new note,
         *     selection and links instead of creating a second copy. The source of a
         *     save is decided by the adapter, never by the request: a request without
         *     a source is recorded as coming from Norte's own dialog, and the only
         *     source a request may carry is the browser extension's.
         */
        post: operations["saveLibraryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count the library by view, kind and unread state
         * @description Every count the library screen shows, in one query, so a list call
         *     never recomputes them.
         */
        get: operations["getLibraryCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/items/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Draw a random unread item
         * @description The serendipity button: one unread item, drawn at random, for the
         *     moment when nothing on the shelf appeals. With away_from_focus the draw
         *     is weighted by 1 / (1 + focus score), so an item unrelated to what the
         *     person is focused on is the likelier one -- which is the point, the
         *     focused ones already having their own view. With away_from_focus false
         *     every unread item is equally likely.
         *
         *     This path is declared before /api/library/items/{id} because the two
         *     overlap: a router that matched the wildcard first would validate a draw
         *     against the detail endpoint.
         *
         *     Draws are with replacement, so the same item may come back twice in one
         *     answer; with a seed the whole answer is reproducible, which is what
         *     makes the weighting testable. A library with no unread item answers 404.
         */
        get: operations["drawLibraryItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one saved link in full
         * @description The whole record, including the extracted text when extraction has
         *     produced it. A read never writes.
         */
        get: operations["getLibraryItem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a saved link
         * @description Only the fields present are applied. Setting unread records or clears
         *     the read event; retitling marks the title as the person's own and
         *     follows the registry row; retyping follows the registry type.
         */
        patch: operations["patchLibraryItem"];
        trace?: never;
    };
    "/api/library/items/{id}/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract a saved link's article text again
         * @description Puts the item back to pending and enqueues the background extraction,
         *     which is how a failed extraction is retried from the reader. The answer
         *     comes back as soon as the job is queued; it never waits for the text.
         *     With refresh true the page is downloaded again and the new HTML becomes
         *     the item's snapshot, which is what to use when the saved snapshot is the
         *     problem rather than the extraction of it.
         */
        post: operations["extractLibraryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/items/{id}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record that a saved link was opened
         * @description Sets when the item was last opened. Opening is not reading: unread is
         *     left exactly as it was.
         */
        post: operations["openLibraryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description What the saved link is. A save always starts as a post; only a patch retypes.
         * @enum {string}
         */
        ItemKind: "post" | "livro" | "paper" | "video" | "podcast" | "newsletter" | "curso";
        /**
         * @description Which shelf the item sits on.
         * @enum {string}
         */
        ItemStatus: "inbox" | "depois" | "arquivo";
        /**
         * @description Where the save came from.
         * @enum {string}
         */
        ItemSource: "app" | "extension" | "cli" | "telegram" | "import";
        /**
         * @description Which shelf a list reads; tudo is every status. now is not a shelf but
         *     the focus-ranked unread list, which is why it sits here rather than in
         *     ItemStatus: a status is something an item has, and now is a way of
         *     looking at the library.
         * @enum {string}
         */
        LibraryView: "inbox" | "depois" | "arquivo" | "tudo" | "now";
        /**
         * @description The order a list comes back in.
         * @enum {string}
         */
        LibrarySort: "saved_desc" | "saved_asc" | "title" | "last_opened_desc";
        /**
         * @description Where the background extraction of this item stands.
         * @enum {string}
         */
        ExtractStatus: "pending" | "done" | "failed";
        /** @description The passage selected when the link was saved, if any. */
        TextSelection: {
            exact?: string;
            prefix?: string;
            suffix?: string;
        };
        /** @description Where the person stopped reading. */
        ReadPosition: {
            v?: number;
            anchor?: string;
            percent?: number;
        };
        SaveItemRequest: {
            /** @description The saved page's address, absolute and http or https. */
            url: string;
            /** @description The tab title, used until extraction gives a better one. */
            title?: string;
            /** @description The page's HTML snapshot, when the saver captured one. */
            html?: string;
            selection?: components["schemas"]["TextSelection"];
            /** @description Why this link was worth keeping. */
            why?: string;
            /** @description Registry ids this item is about; unknown ids refuse the save. */
            link_to?: string[];
            /**
             * @description The only source a request may carry is the browser extension's;
             *     anything else is refused, and an absent source is Norte's own dialog.
             * @enum {string}
             */
            source?: "extension";
        };
        SaveItemResponse: {
            /** @description The saved item, new or already there. */
            id: string;
        };
        ExtractItemRequest: {
            /**
             * @description Download the page again instead of re-reading the stored snapshot,
             *     and make the new HTML the item's snapshot.
             */
            refresh?: boolean;
        };
        ExtractItemResponse: {
            item_id: string;
            /** @description The queued job, so a failure can be found in `norte jobs list`. */
            job_id: string;
            /**
             * @description The generation this retry runs under. Any run still in flight under
             *     an older one is superseded and writes nothing.
             */
            extract_generation: number;
        };
        LibraryItemSummary: {
            id: string;
            kind: components["schemas"]["ItemKind"];
            url: string;
            canonical_url: string;
            title: string;
            /** @description True once the person overrode the extracted title. */
            title_edited: boolean;
            author?: string;
            site?: string;
            published_at?: string;
            lead_image?: string;
            why?: string;
            selection?: components["schemas"]["TextSelection"];
            status: components["schemas"]["ItemStatus"];
            unread: boolean;
            saved_at: string;
            read_at?: string;
            last_opened_at?: string;
            read_position?: components["schemas"]["ReadPosition"];
            source: components["schemas"]["ItemSource"];
            /** @description The snapshot blob in the file store, when one was captured. */
            html_hash?: string;
            content_headings?: string;
            extract_status: components["schemas"]["ExtractStatus"];
            /**
             * @description Bumped by every save that enqueues a new extraction, so the worker
             *     can tell a superseded job from the current one.
             */
            extract_generation: number;
            extracted_at?: string;
            extract_error?: string;
            minutes?: number;
            created_at: string;
            updated_at: string;
        };
        LibraryItem: {
            id: string;
            kind: components["schemas"]["ItemKind"];
            url: string;
            canonical_url: string;
            title: string;
            /** @description True once the person overrode the extracted title. */
            title_edited: boolean;
            author?: string;
            site?: string;
            published_at?: string;
            lead_image?: string;
            why?: string;
            selection?: components["schemas"]["TextSelection"];
            status: components["schemas"]["ItemStatus"];
            unread: boolean;
            saved_at: string;
            read_at?: string;
            last_opened_at?: string;
            read_position?: components["schemas"]["ReadPosition"];
            source: components["schemas"]["ItemSource"];
            /** @description The snapshot blob in the file store, when one was captured. */
            html_hash?: string;
            content_html?: string;
            content_text?: string;
            content_headings?: string;
            extract_status: components["schemas"]["ExtractStatus"];
            /**
             * @description Bumped by every save that enqueues a new extraction, so the worker
             *     can tell a superseded job from the current one.
             */
            extract_generation: number;
            extracted_at?: string;
            extract_error?: string;
            minutes?: number;
            created_at: string;
            updated_at: string;
        };
        LibraryItemList: {
            items: components["schemas"]["LibraryItemSummary"][];
            /** @description The cursor for the following page, absent on the last one. */
            next_cursor?: string;
        };
        LibraryDraw: {
            /**
             * @description One summary per draw, in the order they were drawn. Draws are with
             *     replacement, so an id may appear more than once.
             */
            items: components["schemas"]["LibraryItemSummary"][];
        };
        LibraryCounts: {
            views: {
                inbox: number;
                depois: number;
                arquivo: number;
                tudo: number;
            };
            kinds: {
                post: number;
                livro: number;
                paper: number;
                video: number;
                podcast: number;
                newsletter: number;
                curso: number;
            };
            /** @description Items still unread, over every view. */
            unread: number;
        };
        PatchItemRequest: {
            status?: components["schemas"]["ItemStatus"];
            unread?: boolean;
            why?: string;
            kind?: components["schemas"]["ItemKind"];
            title?: string;
            read_position?: components["schemas"]["ReadPosition"];
        };
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /**
             * @description Stable, machine-readable reason. The frontend branches on this;
             *     the message is for a person.
             * @example invalid_request
             */
            code: string;
            /** @description What went wrong, in one sentence, safe to show. */
            message: string;
            /**
             * @description The input the failure is attributable to, when it is attributable
             *     to exactly one. Absent otherwise.
             * @example kind
             */
            field?: string;
            /**
             * @description The X-Request-Id of the request that failed, so an error a person
             *     reports can be matched to the log line that recorded it.
             */
            request_id: string;
        };
    };
    responses: {
        /**
         * @description Every failure in one envelope, whether it came from validating the
         *     request against this contract or from the domain behind it.
         */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLibraryItems: {
        parameters: {
            query?: {
                /**
                 * @description Which shelf to read; tudo is every status, and now is the
                 *     focus-ranked unread list rather than a shelf.
                 */
                view?: components["schemas"]["LibraryView"];
                /** @description Keep only this kind. */
                tipo?: components["schemas"]["ItemKind"];
                /** @description Keep only unread items, or only read ones. */
                unread?: boolean;
                /**
                 * @description The order. last_opened_desc lists only items that have been
                 *     opened, newest-opened first, and is what the home's "continuar
                 *     lendo" block reads.
                 */
                sort?: components["schemas"]["LibrarySort"];
                /** @description Full-text query over the title, the note and the extracted text. */
                q?: string;
                /** @description The next_cursor of the previous page. */
                cursor?: string;
                /** @description How many summaries a page holds. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveLibraryItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveItemRequest"];
            };
        };
        responses: {
            /** @description The canonical URL was already saved; the existing item, updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveItemResponse"];
                };
            };
            /** @description The save created an item. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveItemResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLibraryCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryCounts"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    drawLibraryItems: {
        parameters: {
            query?: {
                /** @description Weight the draw away from the focus, rather than drawing uniformly. */
                away_from_focus?: boolean;
                /**
                 * @description How many draws this call makes, from 1 to 100. Anything outside
                 *     that range is refused; the range is the service's, so the message
                 *     names it.
                 */
                n?: number;
                /**
                 * @description Makes the draw reproducible: the same seed over the same data draws
                 *     the same items. Without one the draw uses a fresh source.
                 */
                seed?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The items drawn, in draw order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDraw"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getLibraryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItem"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchLibraryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchItemRequest"];
            };
        };
        responses: {
            /** @description The item after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItem"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    extractLibraryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExtractItemRequest"];
            };
        };
        responses: {
            /** @description The extraction was enqueued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractItemResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    openLibraryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item after the opening was recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItem"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
