/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/notes/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List highlights
         * @description Newest first, with the id breaking ties, which is the total order the
         *     cursor continues. Each row carries its source item's title, read from
         *     the registry, so the screen needs no call into the owning module.
         */
        get: operations["listNoteHighlights"];
        put?: never;
        /**
         * Highlight a passage of an item's text
         * @description The client sends the passage and the text around it, never an offset: an
         *     offset into the browser's DOM has no relation to the extracted text the
         *     server anchors against. The server normalises all three, searches the
         *     item's text, and answers with the highlight it stored -- `anchored` on a
         *     unique context match, `orphaned` when the passage is missing or appears
         *     more than once with indistinguishable context.
         */
        post: operations["createNoteHighlight"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/highlights/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a highlight
         * @description The annotations hanging on the highlight go with it, which is what the
         *     foreign key's cascade says; a question written from one of those
         *     annotations keeps its text and loses the reference.
         */
        delete: operations["deleteNoteHighlight"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List annotations */
        get: operations["listNoteAnnotations"];
        put?: never;
        /**
         * Write a note in the margin
         * @description With a highlight id the annotation hangs on that passage; without one it
         *     is a loose note on the item.
         */
        post: operations["createNoteAnnotation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/annotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an annotation */
        delete: operations["deleteNoteAnnotation"];
        options?: never;
        head?: never;
        /** Rewrite an annotation */
        patch: operations["updateNoteAnnotation"];
        trace?: never;
    };
    "/api/notes/items/{item_id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read the one freeform note an item carries
         * @description An item that has never been annotated answers with an empty text rather
         *     than 404: the reader's "Nota" tab is a place to write, and a missing
         *     note is an empty one.
         */
        get: operations["getNoteItemNote"];
        /**
         * Write the one freeform note an item carries
         * @description Replaces whatever was there. An empty text deletes the note, so the tab
         *     does not leave a blank row behind.
         */
        put: operations["putNoteItemNote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List questions */
        get: operations["listNoteQuestions"];
        put?: never;
        /**
         * Write a question
         * @description A single question carries no kind. A kind is set only for a question
         *     written from one of a set's six prompts, and the database refuses any
         *     value outside that list.
         */
        post: operations["createNoteQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a question's text, answer or state
         * @description Only the fields present are applied.
         */
        patch: operations["updateNoteQuestion"];
        trace?: never;
    };
    "/api/notes/question-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List question sets */
        get: operations["listNoteQuestionSets"];
        put?: never;
        /**
         * Open a question set on a topic
         * @description The set stores only the prompts the person actually wrote something
         *     into: six empty boxes are six questions nobody asked. The set is
         *     registered in the item registry as a `question_set`, so a subject can be
         *     linked to it later.
         */
        post: operations["createNoteQuestionSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/question-sets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one question set with its questions */
        get: operations["getNoteQuestionSet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count the notes by kind
         * @description What the sidebar and the Notas tabs print. It is one query rather than
         *     three list calls, so a screen showing the counts never pages a list it
         *     does not render.
         */
        get: operations["getNoteCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Whether the passage was found in the item's current text. An orphaned
         *     highlight is listed as lost rather than hidden: its text is still the
         *     thing the person marked.
         * @enum {string}
         */
        HighlightStatus: "anchored" | "orphaned";
        /**
         * @description Which of a set's six prompts the question came from. A question written
         *     on its own has none.
         * @enum {string}
         */
        QuestionKind: "what" | "why" | "who" | "when" | "where" | "how";
        /**
         * @description Where the question stands.
         * @enum {string}
         */
        QuestionStatus: "open" | "answered" | "dropped";
        /**
         * @description The item a note sits on, as the registry holds it. It is here so a note
         *     row renders its origin with the owning module switched off.
         */
        NoteSource: {
            id: string;
            module: string;
            type: string;
            title: string;
            url?: string;
        };
        NewHighlight: {
            /** @description The registry id of the item the passage belongs to. */
            item_id: string;
            /** @description The selected passage. */
            exact: string;
            /** @description The 32 code points before the passage, as the client saw them. */
            prefix?: string;
            /** @description The 32 code points after the passage, as the client saw them. */
            suffix?: string;
        };
        Highlight: {
            id: string;
            item_id: string;
            /** @description The page or section a PDF or EPUB highlight sits on; null for an article. */
            section_ref?: string;
            /** @description How that page is shown to the person; null for an article. */
            location_label?: string;
            exact: string;
            prefix: string;
            suffix: string;
            /**
             * @description The code-point offset of the passage in the item's text when the
             *     highlight was anchored. It only orders the search for the passage;
             *     it never chooses between two matches on its own.
             */
            position_hint: number;
            status: components["schemas"]["HighlightStatus"];
            /**
             * @description True when the passage was stored orphaned because the text held
             *     several occurrences with indistinguishable context, as opposed to
             *     none at all. The reader says which of the two happened.
             */
            ambiguous?: boolean;
            created_at: string;
            source?: components["schemas"]["NoteSource"];
        };
        HighlightList: {
            items: components["schemas"]["Highlight"][];
            next_cursor?: string;
        };
        NewAnnotation: {
            item_id: string;
            /** @description The highlight this note hangs on, when it hangs on one. */
            highlight_id?: string;
            text: string;
        };
        AnnotationPatch: {
            text: string;
        };
        Annotation: {
            id: string;
            item_id: string;
            highlight_id?: string;
            /** @description The highlighted passage this note hangs on, when it hangs on one. */
            quote?: string;
            text: string;
            created_at: string;
            updated_at: string;
            source?: components["schemas"]["NoteSource"];
        };
        AnnotationList: {
            items: components["schemas"]["Annotation"][];
            next_cursor?: string;
        };
        ItemNoteBody: {
            text: string;
        };
        ItemNote: {
            /** @description Absent while the item has no note yet. */
            id?: string;
            item_id: string;
            text: string;
            created_at?: string;
            updated_at?: string;
        };
        NewQuestion: {
            /** @description The item the question came out of, when it came out of one. */
            item_id?: string;
            /** @description The margin note the question was turned into, when it was. */
            annotation_id?: string;
            /** @description The set this question belongs to. */
            set_id?: string;
            kind?: components["schemas"]["QuestionKind"];
            text: string;
        };
        QuestionPatch: {
            text?: string;
            answer?: string;
            status?: components["schemas"]["QuestionStatus"];
        };
        Question: {
            id: string;
            item_id?: string;
            annotation_id?: string;
            set_id?: string;
            kind?: components["schemas"]["QuestionKind"];
            text: string;
            answer?: string;
            status: components["schemas"]["QuestionStatus"];
            created_at: string;
            updated_at: string;
            source?: components["schemas"]["NoteSource"];
        };
        QuestionList: {
            items: components["schemas"]["Question"][];
            next_cursor?: string;
        };
        QuestionSetPrompt: {
            kind: components["schemas"]["QuestionKind"];
            /**
             * @description What the person wrote into that prompt. A prompt left blank is not
             *     sent, and one sent blank stores no question.
             */
            text: string;
        };
        NewQuestionSet: {
            topic: string;
            /** @description The prompts the person filled in, at most one per kind. */
            questions?: components["schemas"]["QuestionSetPrompt"][];
        };
        QuestionSet: {
            id: string;
            topic: string;
            question_count: number;
            created_at: string;
        };
        QuestionSetDetail: {
            id: string;
            topic: string;
            question_count: number;
            created_at: string;
            questions: components["schemas"]["Question"][];
        };
        QuestionSetList: {
            items: components["schemas"]["QuestionSet"][];
            next_cursor?: string;
        };
        NoteCounts: {
            highlights: number;
            anotacoes: number;
            perguntas: number;
            conjuntos: number;
        };
        ErrorDetail: {
            code: string;
            message: string;
            field?: string;
            request_id: string;
        };
        Error: {
            error: components["schemas"]["ErrorDetail"];
        };
    };
    responses: {
        /**
         * @description Every failure in one envelope, whether it came from validating the
         *     request against this contract or from the domain behind it.
         */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PathID: string;
        PathItemID: string;
        /** @description Keep only the notes of this item. */
        ItemFilter: string;
        /**
         * @description Keep only the rows whose own text, or whose source item's title,
         *     contains this. The match is case-insensitive and is a substring rather
         *     than a word query: the filter is a screen's narrowing box, not a search.
         */
        TextFilter: string;
        /** @description The next_cursor of the previous page. */
        Cursor: string;
        /** @description How many rows a page holds. */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listNoteHighlights: {
        parameters: {
            query?: {
                /** @description Keep only the notes of this item. */
                item_id?: components["parameters"]["ItemFilter"];
                /**
                 * @description Keep only the rows whose own text, or whose source item's title,
                 *     contains this. The match is case-insensitive and is a substring rather
                 *     than a word query: the filter is a screen's narrowing box, not a search.
                 */
                q?: components["parameters"]["TextFilter"];
                /** @description The next_cursor of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many rows a page holds. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of highlights. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNoteHighlight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewHighlight"];
            };
        };
        responses: {
            /** @description The highlight was stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Highlight"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteNoteHighlight: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The highlight is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listNoteAnnotations: {
        parameters: {
            query?: {
                /** @description Keep only the notes of this item. */
                item_id?: components["parameters"]["ItemFilter"];
                /**
                 * @description Keep only the rows whose own text, or whose source item's title,
                 *     contains this. The match is case-insensitive and is a substring rather
                 *     than a word query: the filter is a screen's narrowing box, not a search.
                 */
                q?: components["parameters"]["TextFilter"];
                /** @description The next_cursor of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many rows a page holds. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of annotations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnotationList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNoteAnnotation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAnnotation"];
            };
        };
        responses: {
            /** @description The annotation was stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteNoteAnnotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The annotation is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    updateNoteAnnotation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnotationPatch"];
            };
        };
        responses: {
            /** @description The annotation after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Annotation"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNoteItemNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: components["parameters"]["PathItemID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The note, empty when none was written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemNote"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putNoteItemNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: components["parameters"]["PathItemID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemNoteBody"];
            };
        };
        responses: {
            /** @description The note after the write. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemNote"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listNoteQuestions: {
        parameters: {
            query?: {
                /** @description Keep only the notes of this item. */
                item_id?: components["parameters"]["ItemFilter"];
                /** @description Keep only the questions of this set. */
                set_id?: string;
                /** @description Keep only questions in this state. */
                status?: components["schemas"]["QuestionStatus"];
                /**
                 * @description Keep only the rows whose own text, or whose source item's title,
                 *     contains this. The match is case-insensitive and is a substring rather
                 *     than a word query: the filter is a screen's narrowing box, not a search.
                 */
                q?: components["parameters"]["TextFilter"];
                /** @description The next_cursor of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many rows a page holds. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of questions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNoteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewQuestion"];
            };
        };
        responses: {
            /** @description The question was stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateNoteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionPatch"];
            };
        };
        responses: {
            /** @description The question after the change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Question"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listNoteQuestionSets: {
        parameters: {
            query?: {
                /**
                 * @description Keep only the rows whose own text, or whose source item's title,
                 *     contains this. The match is case-insensitive and is a substring rather
                 *     than a word query: the filter is a screen's narrowing box, not a search.
                 */
                q?: components["parameters"]["TextFilter"];
                /** @description The next_cursor of the previous page. */
                cursor?: components["parameters"]["Cursor"];
                /** @description How many rows a page holds. */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of sets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSetList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createNoteQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewQuestionSet"];
            };
        };
        responses: {
            /** @description The set and the questions it stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSetDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNoteQuestionSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The set. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSetDetail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getNoteCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteCounts"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
