// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type NotesAnnotation struct {
	ID          string
	ItemID      string
	HighlightID sql.NullString
	Text        string
	CreatedAt   string
	UpdatedAt   string
}

type NotesHighlight struct {
	ID            string
	ItemID        string
	SectionRef    sql.NullString
	LocationLabel sql.NullString
	Exact         string
	Prefix        string
	Suffix        string
	PositionHint  int64
	Status        string
	CreatedAt     string
}

type NotesNote struct {
	ID        string
	ItemID    string
	Text      string
	CreatedAt string
	UpdatedAt string
}

type NotesQuestion struct {
	ID           string
	ItemID       sql.NullString
	AnnotationID sql.NullString
	SetID        sql.NullString
	Kind         sql.NullString
	Text         string
	Answer       sql.NullString
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

type NotesQuestionSet struct {
	ID        string
	Topic     string
	CreatedAt string
}
