// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
	"database/sql"
)

const countNotesAnnotations = `-- name: CountNotesAnnotations :one
SELECT COUNT(*) FROM notes_annotations
`

func (q *Queries) CountNotesAnnotations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotesAnnotations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotesHighlights = `-- name: CountNotesHighlights :one
SELECT COUNT(*) FROM notes_highlights
`

func (q *Queries) CountNotesHighlights(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotesHighlights)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotesQuestionSets = `-- name: CountNotesQuestionSets :one
SELECT COUNT(*) FROM notes_question_sets
`

func (q *Queries) CountNotesQuestionSets(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotesQuestionSets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotesQuestions = `-- name: CountNotesQuestions :one
SELECT COUNT(*) FROM notes_questions
`

func (q *Queries) CountNotesQuestions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotesQuestions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotesQuestionsInSet = `-- name: CountNotesQuestionsInSet :one
SELECT COUNT(*) FROM notes_questions WHERE set_id = ?
`

func (q *Queries) CountNotesQuestionsInSet(ctx context.Context, setID sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotesQuestionsInSet, setID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteNotesAnnotation = `-- name: DeleteNotesAnnotation :execresult
DELETE FROM notes_annotations WHERE id = ?
`

func (q *Queries) DeleteNotesAnnotation(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNotesAnnotation, id)
}

const deleteNotesHighlight = `-- name: DeleteNotesHighlight :execresult
DELETE FROM notes_highlights WHERE id = ?
`

func (q *Queries) DeleteNotesHighlight(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNotesHighlight, id)
}

const deleteNotesItemNote = `-- name: DeleteNotesItemNote :execresult
DELETE FROM notes_notes WHERE item_id = ?
`

func (q *Queries) DeleteNotesItemNote(ctx context.Context, itemID string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteNotesItemNote, itemID)
}

const getNotesAnnotationByID = `-- name: GetNotesAnnotationByID :one
SELECT id, item_id, highlight_id, text, created_at, updated_at
FROM notes_annotations WHERE id = ?
`

func (q *Queries) GetNotesAnnotationByID(ctx context.Context, id string) (NotesAnnotation, error) {
	row := q.db.QueryRowContext(ctx, getNotesAnnotationByID, id)
	var i NotesAnnotation
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.HighlightID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesHighlightByID = `-- name: GetNotesHighlightByID :one
SELECT id, item_id, section_ref, location_label, exact, prefix, suffix,
       position_hint, status, created_at
FROM notes_highlights WHERE id = ?
`

func (q *Queries) GetNotesHighlightByID(ctx context.Context, id string) (NotesHighlight, error) {
	row := q.db.QueryRowContext(ctx, getNotesHighlightByID, id)
	var i NotesHighlight
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.SectionRef,
		&i.LocationLabel,
		&i.Exact,
		&i.Prefix,
		&i.Suffix,
		&i.PositionHint,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getNotesItemNote = `-- name: GetNotesItemNote :one
SELECT id, item_id, text, created_at, updated_at FROM notes_notes WHERE item_id = ?
`

func (q *Queries) GetNotesItemNote(ctx context.Context, itemID string) (NotesNote, error) {
	row := q.db.QueryRowContext(ctx, getNotesItemNote, itemID)
	var i NotesNote
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesQuestionByID = `-- name: GetNotesQuestionByID :one
SELECT id, item_id, annotation_id, set_id, kind, text, answer, status, created_at, updated_at
FROM notes_questions WHERE id = ?
`

func (q *Queries) GetNotesQuestionByID(ctx context.Context, id string) (NotesQuestion, error) {
	row := q.db.QueryRowContext(ctx, getNotesQuestionByID, id)
	var i NotesQuestion
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.AnnotationID,
		&i.SetID,
		&i.Kind,
		&i.Text,
		&i.Answer,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotesQuestionSetByID = `-- name: GetNotesQuestionSetByID :one
SELECT id, topic, created_at FROM notes_question_sets WHERE id = ?
`

func (q *Queries) GetNotesQuestionSetByID(ctx context.Context, id string) (NotesQuestionSet, error) {
	row := q.db.QueryRowContext(ctx, getNotesQuestionSetByID, id)
	var i NotesQuestionSet
	err := row.Scan(&i.ID, &i.Topic, &i.CreatedAt)
	return i, err
}

const insertNotesAnnotation = `-- name: InsertNotesAnnotation :exec
INSERT INTO notes_annotations (id, item_id, highlight_id, text, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertNotesAnnotationParams struct {
	ID          string
	ItemID      string
	HighlightID sql.NullString
	Text        string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) InsertNotesAnnotation(ctx context.Context, arg InsertNotesAnnotationParams) error {
	_, err := q.db.ExecContext(ctx, insertNotesAnnotation,
		arg.ID,
		arg.ItemID,
		arg.HighlightID,
		arg.Text,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertNotesHighlight = `-- name: InsertNotesHighlight :exec

INSERT INTO notes_highlights (
    id, item_id, section_ref, location_label, exact, prefix, suffix,
    position_hint, status, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNotesHighlightParams struct {
	ID            string
	ItemID        string
	SectionRef    sql.NullString
	LocationLabel sql.NullString
	Exact         string
	Prefix        string
	Suffix        string
	PositionHint  int64
	Status        string
	CreatedAt     string
}

// The notes module's own statements. Every one of them reads only notes_*
// tables, because a module's queries must not compile against another module's
// tables -- that rule is what lets a module be switched off.
//
// The lists are built in Go instead: each one joins core_items for the source
// title, which belongs to the core rather than to this module, and each one's
// WHERE clause and cursor predicate change with the filters a fixed statement
// cannot name.
func (q *Queries) InsertNotesHighlight(ctx context.Context, arg InsertNotesHighlightParams) error {
	_, err := q.db.ExecContext(ctx, insertNotesHighlight,
		arg.ID,
		arg.ItemID,
		arg.SectionRef,
		arg.LocationLabel,
		arg.Exact,
		arg.Prefix,
		arg.Suffix,
		arg.PositionHint,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertNotesQuestion = `-- name: InsertNotesQuestion :exec
INSERT INTO notes_questions (
    id, item_id, annotation_id, set_id, kind, text, answer, status, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNotesQuestionParams struct {
	ID           string
	ItemID       sql.NullString
	AnnotationID sql.NullString
	SetID        sql.NullString
	Kind         sql.NullString
	Text         string
	Answer       sql.NullString
	Status       string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) InsertNotesQuestion(ctx context.Context, arg InsertNotesQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertNotesQuestion,
		arg.ID,
		arg.ItemID,
		arg.AnnotationID,
		arg.SetID,
		arg.Kind,
		arg.Text,
		arg.Answer,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertNotesQuestionSet = `-- name: InsertNotesQuestionSet :exec
INSERT INTO notes_question_sets (id, topic, created_at) VALUES (?, ?, ?)
`

type InsertNotesQuestionSetParams struct {
	ID        string
	Topic     string
	CreatedAt string
}

func (q *Queries) InsertNotesQuestionSet(ctx context.Context, arg InsertNotesQuestionSetParams) error {
	_, err := q.db.ExecContext(ctx, insertNotesQuestionSet, arg.ID, arg.Topic, arg.CreatedAt)
	return err
}

const listNotesHighlightsForItem = `-- name: ListNotesHighlightsForItem :many
SELECT id, item_id, section_ref, location_label, exact, prefix, suffix,
       position_hint, status, created_at
FROM notes_highlights WHERE item_id = ? ORDER BY created_at, id
`

func (q *Queries) ListNotesHighlightsForItem(ctx context.Context, itemID string) ([]NotesHighlight, error) {
	rows, err := q.db.QueryContext(ctx, listNotesHighlightsForItem, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotesHighlight{}
	for rows.Next() {
		var i NotesHighlight
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.SectionRef,
			&i.LocationLabel,
			&i.Exact,
			&i.Prefix,
			&i.Suffix,
			&i.PositionHint,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesItemIDsWithHighlights = `-- name: ListNotesItemIDsWithHighlights :many
SELECT DISTINCT item_id FROM notes_highlights ORDER BY item_id
`

func (q *Queries) ListNotesItemIDsWithHighlights(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNotesItemIDsWithHighlights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesQuestionsForSet = `-- name: ListNotesQuestionsForSet :many
SELECT id, item_id, annotation_id, set_id, kind, text, answer, status, created_at, updated_at
FROM notes_questions WHERE set_id = ? ORDER BY created_at, id
`

func (q *Queries) ListNotesQuestionsForSet(ctx context.Context, setID sql.NullString) ([]NotesQuestion, error) {
	rows, err := q.db.QueryContext(ctx, listNotesQuestionsForSet, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotesQuestion{}
	for rows.Next() {
		var i NotesQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.AnnotationID,
			&i.SetID,
			&i.Kind,
			&i.Text,
			&i.Answer,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotesHighlightAnchor = `-- name: SetNotesHighlightAnchor :exec
UPDATE notes_highlights SET status = ?, position_hint = ? WHERE id = ?
`

type SetNotesHighlightAnchorParams struct {
	Status       string
	PositionHint int64
	ID           string
}

// Re-anchoring writes both columns at once: a status without the hint it was
// computed from would order the next search from a stale position.
func (q *Queries) SetNotesHighlightAnchor(ctx context.Context, arg SetNotesHighlightAnchorParams) error {
	_, err := q.db.ExecContext(ctx, setNotesHighlightAnchor, arg.Status, arg.PositionHint, arg.ID)
	return err
}

const updateNotesAnnotationText = `-- name: UpdateNotesAnnotationText :execresult
UPDATE notes_annotations SET text = ?, updated_at = ? WHERE id = ?
`

type UpdateNotesAnnotationTextParams struct {
	Text      string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateNotesAnnotationText(ctx context.Context, arg UpdateNotesAnnotationTextParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNotesAnnotationText, arg.Text, arg.UpdatedAt, arg.ID)
}

const updateNotesQuestion = `-- name: UpdateNotesQuestion :execresult
UPDATE notes_questions SET text = ?, answer = ?, status = ?, updated_at = ? WHERE id = ?
`

type UpdateNotesQuestionParams struct {
	Text      string
	Answer    sql.NullString
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateNotesQuestion(ctx context.Context, arg UpdateNotesQuestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateNotesQuestion,
		arg.Text,
		arg.Answer,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}

const upsertNotesItemNote = `-- name: UpsertNotesItemNote :exec
INSERT INTO notes_notes (id, item_id, text, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (item_id) DO UPDATE SET text = excluded.text, updated_at = excluded.updated_at
`

type UpsertNotesItemNoteParams struct {
	ID        string
	ItemID    string
	Text      string
	CreatedAt string
	UpdatedAt string
}

// The one note per item is written by id on conflict with the item: a PUT is a
// replacement, and two writes of the same tab must not leave two rows.
func (q *Queries) UpsertNotesItemNote(ctx context.Context, arg UpsertNotesItemNoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotesItemNote,
		arg.ID,
		arg.ItemID,
		arg.Text,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
