// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package db

import (
	"context"
	"database/sql"
)

const confirmCoreLink = `-- name: ConfirmCoreLink :exec
INSERT INTO core_links (id, src_id, dst_id, kind, source, status, confidence, created_at, decided_at)
VALUES (?, ?, ?, ?, 'manual', 'confirmed', NULL, ?, ?)
ON CONFLICT (src_id, dst_id, kind) DO UPDATE SET
    source     = 'manual',
    status     = 'confirmed',
    decided_at = excluded.decided_at
WHERE core_links.status <> 'confirmed'
`

type ConfirmCoreLinkParams struct {
	ID        string
	SrcID     string
	DstID     string
	Kind      string
	CreatedAt string
	DecidedAt sql.NullString
}

// Insert a manual, confirmed link, or take over whatever decision was on that
// triple before. The WHERE on the conflict branch is what makes confirming an
// already confirmed link a no-op, rather than moving the date it was decided.
func (q *Queries) ConfirmCoreLink(ctx context.Context, arg ConfirmCoreLinkParams) error {
	_, err := q.db.ExecContext(ctx, confirmCoreLink,
		arg.ID,
		arg.SrcID,
		arg.DstID,
		arg.Kind,
		arg.CreatedAt,
		arg.DecidedAt,
	)
	return err
}

const deleteCollectableCoreFile = `-- name: DeleteCollectableCoreFile :execresult
DELETE FROM core_files WHERE core_files.hash = ?
  AND NOT EXISTS (SELECT 1 FROM core_file_refs WHERE core_file_refs.hash = ?)
`

type DeleteCollectableCoreFileParams struct {
	Hash   string
	Hash_2 string
}

// The no-references condition is repeated here so a reference written since the
// listing wins over the collector.
func (q *Queries) DeleteCollectableCoreFile(ctx context.Context, arg DeleteCollectableCoreFileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCollectableCoreFile, arg.Hash, arg.Hash_2)
}

const deleteCoreItem = `-- name: DeleteCoreItem :execresult
DELETE FROM core_items WHERE id = ?
`

func (q *Queries) DeleteCoreItem(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCoreItem, id)
}

const getCoreItemByID = `-- name: GetCoreItemByID :one
SELECT id, module, type, title, url, created_at FROM core_items WHERE id = ?
`

// The registry row behind one id, which is how a module renders an item it does
// not own: the title and the type are here, so a note shows where it came from
// with the owning module switched off.
func (q *Queries) GetCoreItemByID(ctx context.Context, id string) (CoreItem, error) {
	row := q.db.QueryRowContext(ctx, getCoreItemByID, id)
	var i CoreItem
	err := row.Scan(
		&i.ID,
		&i.Module,
		&i.Type,
		&i.Title,
		&i.Url,
		&i.CreatedAt,
	)
	return i, err
}

const insertCoreFile = `-- name: InsertCoreFile :exec
INSERT INTO core_files (hash, media_type, size, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT (hash) DO UPDATE SET created_at = excluded.created_at
`

type InsertCoreFileParams struct {
	Hash      string
	MediaType string
	Size      int64
	CreatedAt string
}

// Storing bytes that already exist refreshes created_at on purpose. The grace
// period protects a blob between Store and the transaction that references it,
// and a second Store opens exactly such a window again; keeping an old
// unreferenced row's timestamp would let gc delete the blob under that caller.
// A referenced blob is never collected, so the refresh changes nothing for it.
func (q *Queries) InsertCoreFile(ctx context.Context, arg InsertCoreFileParams) error {
	_, err := q.db.ExecContext(ctx, insertCoreFile,
		arg.Hash,
		arg.MediaType,
		arg.Size,
		arg.CreatedAt,
	)
	return err
}

const insertCoreItem = `-- name: InsertCoreItem :exec
INSERT INTO core_items (id, module, type, title, url, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCoreItemParams struct {
	ID        string
	Module    string
	Type      string
	Title     string
	Url       sql.NullString
	CreatedAt string
}

func (q *Queries) InsertCoreItem(ctx context.Context, arg InsertCoreItemParams) error {
	_, err := q.db.ExecContext(ctx, insertCoreItem,
		arg.ID,
		arg.Module,
		arg.Type,
		arg.Title,
		arg.Url,
		arg.CreatedAt,
	)
	return err
}

const listCollectableCoreFiles = `-- name: ListCollectableCoreFiles :many
SELECT core_files.hash, core_files.size FROM core_files
WHERE core_files.created_at < ?
  AND NOT EXISTS (SELECT 1 FROM core_file_refs WHERE core_file_refs.hash = core_files.hash)
ORDER BY hash
`

type ListCollectableCoreFilesRow struct {
	Hash string
	Size int64
}

func (q *Queries) ListCollectableCoreFiles(ctx context.Context, createdAt string) ([]ListCollectableCoreFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectableCoreFiles, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectableCoreFilesRow{}
	for rows.Next() {
		var i ListCollectableCoreFilesRow
		if err := rows.Scan(&i.Hash, &i.Size); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suggestCoreLink = `-- name: SuggestCoreLink :exec
INSERT INTO core_links (id, src_id, dst_id, kind, source, status, confidence, created_at, decided_at)
VALUES (?, ?, ?, ?, 'llm', 'suggested', ?, ?, NULL)
ON CONFLICT (src_id, dst_id, kind) DO UPDATE SET
    confidence = excluded.confidence
WHERE core_links.status = 'suggested'
`

type SuggestCoreLinkParams struct {
	ID         string
	SrcID      string
	DstID      string
	Kind       string
	Confidence sql.NullFloat64
	CreatedAt  string
}

// Record what the model thinks. The WHERE on the conflict branch is what keeps a
// re-run from putting a rejected link back in the review queue.
func (q *Queries) SuggestCoreLink(ctx context.Context, arg SuggestCoreLinkParams) error {
	_, err := q.db.ExecContext(ctx, suggestCoreLink,
		arg.ID,
		arg.SrcID,
		arg.DstID,
		arg.Kind,
		arg.Confidence,
		arg.CreatedAt,
	)
	return err
}

const updateCoreItem = `-- name: UpdateCoreItem :execresult
UPDATE core_items SET title = ?, type = ? WHERE id = ?
`

type UpdateCoreItemParams struct {
	Title string
	Type  string
	ID    string
}

func (q *Queries) UpdateCoreItem(ctx context.Context, arg UpdateCoreItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCoreItem, arg.Title, arg.Type, arg.ID)
}
