// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"database/sql"
)

const findOutstandingCoreJobByDedupeKey = `-- name: FindOutstandingCoreJobByDedupeKey :one
SELECT id FROM core_jobs WHERE dedupe_key = ? AND status IN ('queued', 'running') LIMIT 1
`

func (q *Queries) FindOutstandingCoreJobByDedupeKey(ctx context.Context, dedupeKey sql.NullString) (string, error) {
	row := q.db.QueryRowContext(ctx, findOutstandingCoreJobByDedupeKey, dedupeKey)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getCoreJobByID = `-- name: GetCoreJobByID :one
SELECT id, kind, payload, dedupe_key, status, attempts, available_at, lease_until, lease_owner, last_error, created_at, started_at, finished_at
FROM core_jobs WHERE id = ?
`

func (q *Queries) GetCoreJobByID(ctx context.Context, id string) (CoreJob, error) {
	row := q.db.QueryRowContext(ctx, getCoreJobByID, id)
	var i CoreJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LeaseUntil,
		&i.LeaseOwner,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertCoreJob = `-- name: InsertCoreJob :exec

INSERT INTO core_jobs (id, kind, payload, dedupe_key, status, attempts, available_at, lease_until, lease_owner, last_error, created_at, started_at, finished_at)
VALUES (?, ?, ?, ?, 'queued', 0, ?, NULL, NULL, NULL, ?, NULL, NULL)
`

type InsertCoreJobParams struct {
	ID          string
	Kind        string
	Payload     string
	DedupeKey   sql.NullString
	AvailableAt string
	CreatedAt   string
}

// The durable jobs queue. The worker in internal/core/jobs.go leases from
// core_jobs; this file holds every statement it and the `norte jobs` commands
// need. The claim itself is built in Go because the list of registered kinds
// varies at runtime, so it cannot be a fixed sqlc query.
func (q *Queries) InsertCoreJob(ctx context.Context, arg InsertCoreJobParams) error {
	_, err := q.db.ExecContext(ctx, insertCoreJob,
		arg.ID,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
		arg.AvailableAt,
		arg.CreatedAt,
	)
	return err
}

const listCoreJobs = `-- name: ListCoreJobs :many
SELECT id, kind, status, attempts, available_at, last_error FROM core_jobs ORDER BY available_at, id
`

type ListCoreJobsRow struct {
	ID          string
	Kind        string
	Status      string
	Attempts    int64
	AvailableAt string
	LastError   sql.NullString
}

func (q *Queries) ListCoreJobs(ctx context.Context) ([]ListCoreJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCoreJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoreJobsRow{}
	for rows.Next() {
		var i ListCoreJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCoreJobDone = `-- name: MarkCoreJobDone :execresult
UPDATE core_jobs SET status = 'done', finished_at = ?, lease_until = NULL, lease_owner = NULL
WHERE id = ? AND status = 'running' AND lease_owner = ?
`

type MarkCoreJobDoneParams struct {
	FinishedAt sql.NullString
	ID         string
	LeaseOwner sql.NullString
}

func (q *Queries) MarkCoreJobDone(ctx context.Context, arg MarkCoreJobDoneParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markCoreJobDone, arg.FinishedAt, arg.ID, arg.LeaseOwner)
}

const markCoreJobFailedPermanent = `-- name: MarkCoreJobFailedPermanent :execresult
UPDATE core_jobs SET status = 'failed', finished_at = ?, last_error = ?, lease_until = NULL, lease_owner = NULL
WHERE id = ? AND status = 'running' AND lease_owner = ?
`

type MarkCoreJobFailedPermanentParams struct {
	FinishedAt sql.NullString
	LastError  sql.NullString
	ID         string
	LeaseOwner sql.NullString
}

func (q *Queries) MarkCoreJobFailedPermanent(ctx context.Context, arg MarkCoreJobFailedPermanentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markCoreJobFailedPermanent,
		arg.FinishedAt,
		arg.LastError,
		arg.ID,
		arg.LeaseOwner,
	)
}

const markCoreJobFailedRetry = `-- name: MarkCoreJobFailedRetry :execresult
UPDATE core_jobs SET status = 'queued', available_at = ?, last_error = ?, lease_until = NULL, lease_owner = NULL
WHERE id = ? AND status = 'running' AND lease_owner = ?
`

type MarkCoreJobFailedRetryParams struct {
	AvailableAt string
	LastError   sql.NullString
	ID          string
	LeaseOwner  sql.NullString
}

func (q *Queries) MarkCoreJobFailedRetry(ctx context.Context, arg MarkCoreJobFailedRetryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markCoreJobFailedRetry,
		arg.AvailableAt,
		arg.LastError,
		arg.ID,
		arg.LeaseOwner,
	)
}

const reclaimExpiredCoreJobs = `-- name: ReclaimExpiredCoreJobs :execresult
UPDATE core_jobs SET status = 'queued', lease_until = NULL, lease_owner = NULL
WHERE status = 'running' AND lease_until IS NOT NULL AND lease_until <= ?
`

func (q *Queries) ReclaimExpiredCoreJobs(ctx context.Context, leaseUntil sql.NullString) (sql.Result, error) {
	return q.db.ExecContext(ctx, reclaimExpiredCoreJobs, leaseUntil)
}

const releaseCoreJobOnShutdown = `-- name: ReleaseCoreJobOnShutdown :execresult
UPDATE core_jobs SET status = 'queued', lease_until = NULL, lease_owner = NULL, attempts = attempts - 1, available_at = ?, started_at = NULL
WHERE id = ? AND status = 'running' AND lease_owner = ?
`

type ReleaseCoreJobOnShutdownParams struct {
	AvailableAt string
	ID          string
	LeaseOwner  sql.NullString
}

func (q *Queries) ReleaseCoreJobOnShutdown(ctx context.Context, arg ReleaseCoreJobOnShutdownParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, releaseCoreJobOnShutdown, arg.AvailableAt, arg.ID, arg.LeaseOwner)
}

const renewCoreJobLease = `-- name: RenewCoreJobLease :execresult
UPDATE core_jobs SET lease_until = ? WHERE id = ? AND status = 'running' AND lease_owner = ?
`

type RenewCoreJobLeaseParams struct {
	LeaseUntil sql.NullString
	ID         string
	LeaseOwner sql.NullString
}

func (q *Queries) RenewCoreJobLease(ctx context.Context, arg RenewCoreJobLeaseParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, renewCoreJobLease, arg.LeaseUntil, arg.ID, arg.LeaseOwner)
}

const retryCoreJob = `-- name: RetryCoreJob :execresult
UPDATE core_jobs SET status = 'queued', attempts = 0, available_at = ?, lease_until = NULL, lease_owner = NULL, started_at = NULL, finished_at = NULL, last_error = NULL
WHERE id = ? AND status = 'failed'
`

type RetryCoreJobParams struct {
	AvailableAt string
	ID          string
}

func (q *Queries) RetryCoreJob(ctx context.Context, arg RetryCoreJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, retryCoreJob, arg.AvailableAt, arg.ID)
}
