// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CoreFile struct {
	Hash      string
	MediaType string
	Size      int64
	CreatedAt string
}

type CoreFileRef struct {
	Hash    string
	OwnerID string
	Kind    string
}

type CoreItem struct {
	ID        string
	Module    string
	Type      string
	Title     string
	Url       sql.NullString
	CreatedAt string
}

type CoreJob struct {
	ID          string
	Kind        string
	Payload     string
	DedupeKey   sql.NullString
	Status      string
	Attempts    int64
	AvailableAt string
	LeaseUntil  sql.NullString
	LeaseOwner  sql.NullString
	LastError   sql.NullString
	CreatedAt   string
	StartedAt   sql.NullString
	FinishedAt  sql.NullString
}

type CoreLink struct {
	ID         string
	SrcID      string
	DstID      string
	Kind       string
	Source     string
	Status     string
	Confidence sql.NullFloat64
	CreatedAt  string
	DecidedAt  sql.NullString
}

type CoreSetting struct {
	Key       string
	Value     string
	UpdatedAt string
}

type CoreSubject struct {
	ID        string
	Name      string
	Slug      string
	Focus     int64
	CreatedAt string
}

type CoreSubjectAlias struct {
	AliasSlug string
	SubjectID string
}
